workflows:
  android-workflow:
    name: Smart Trade Tracker Android APK Build
    max_build_duration: 60
    environment:
      java: 17
      android_signing:
        - smart_trade_tracker_keystore
      groups:
        - google_play
    scripts:
      - name: Set executable permission
        script: chmod +x ./gradlew

      - name: Build APK
        script: |
          cd android
          ./gradlew clean assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - maximemoreau087@gmail.com