workflows:
  android-apk:
    name: Smart Trade Tracker APK
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Build APK
        script: |
          cd android-app
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android-app/app/build/outputs/**/*.apk