workflows:
  android-workflow:
    name: Smart Trade Tracker Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
      android_signing:
        - smart_trade_tracker_keystore
      groups:
        - google_play
    scripts:
      - name: Set executable permission
        script: chmod +x ./gradlew

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease

      - name: Build AAB
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - YOUR_EMAIL_HERE